# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pspGlobal <- function(model, control, save = FALSE, path = ".", quiet = FALSE) {
    .Call(`_psp_pspGlobal`, model, control, save, path, quiet)
}

